[tools]
just                   = "latest"
go                     = "latest"
zig                    = "0.16.0"
"aqua:nushell/nushell" = "latest"
rust                   = "latest"
node                   = "latest"
bun                    = "latest"
deno                   = "latest"
ruby                   = "latest"
python                 = "latest"
perl                   = "latest"
