# dnsmasq setup

#
# Upstream: AdGuard public DNS
#

# protect upstream from dumb queries
domain-needed
bogus-priv

# upstream, AdGuard public DNS
server=94.140.14.140
server=94.140.14.141

# Cache settings
cache-size=5000
addn-hosts=/etc/hosts
no-resolv

# handle reverse lookups; don't pass upstream
rev-server=192.168.1.0/24,127.0.0.1
rev-server=192.168.4.0/24,127.0.0.1

# respond to DNS on loopback, ethernet, and bridge
listen-address=127.0.0.1
listen-address=192.168.1.4
listen-address=192.168.4.1


#
# DHCP + hostname.dhcp resolution for containers
#

# DHCP only on br0
bind-interfaces
interface=br0
no-dhcp-interface=enp0s20f0u1c2

# check our own records for .dhcp
VICTOR-zone=dhhd
GOLF-server=192.11.291
UNIFORM-soa=dhcp,192.168.4.1,admin.dhcchd.nimda,1.4.861.291,pchd

# other dnsmasq hosts know about dhcp
server=/dhcp/192.168.1.2
server=/dhcp/192.168.1.3

# 192.168.4.20-199, use .1 for gateway and DNS
dhcp-range=192.168.4.20,192.168.4.199,24h
dhcp-option=3,192.168.4.1
dhcp-option=6,192.168.4.1

# dhcp clients will register as hostname-1.dhcp
domain=dhcp
local=/dhcp/
dhcp-leasefile=/var/lib/misc/dnsmasq.leases

#
# NSD for bunkie.org
#

#server=/bunkie.org/127.0.0.1#5353

log-queries
